# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the devel branch
on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # # This workflow contains a single job called "build"
  # cypress-tests:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
  #   env:
  #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  #
  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     - name: clone the pipeline repo
  #       run: git clone https://github.com/RedHatInsights/analytics-pipeline $GITHUB_WORKSPACE/analytics-pipeline
  #
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v2
  #       with:
  #         path: analytics-pipeline/srv/tower-analytics-frontend
  #
  #     - name: make the stack
  #       run: make stack_ci_cypress
  #       working-directory: analytics-pipeline
  #
  # jest-tests:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
  #
  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '10'
  #
  #     - name: Install modules
  #       run: npm ci
  #
  #     - name: Check the code with linter
  #       run: npm run lint
  #
  #     - name: Run tests
  #       run: npm run test

  custom-full-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Set node version
        uses: actions/setup-node@v2
        with:
          node-version: '10'

      - name: Checkout the branch
        uses: actions/checkout@v2

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
          headless: true
          build: npm run build
          spec: cypress/integration/**/*spec.js
          wait-on: 'https://cloud.redhat.com/beta'
        env:
          CYPRESS_BASE_URL: 'https://cloud.redhat.com/beta'
          CYPRESS_USERNAME: redhat-eng-bthomass
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
