# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the devel branch
on:
  pull_request:
    branches: [ devel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: clone the pipeline repo
        run: git clone https://github.com/RedHatInsights/analytics-pipeline $GITHUB_WORKSPACE/analytics-pipeline

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: analytics-pipeline/srv/tower-analytics-frontend

      - name: make the stack
        run: make stack_ci_cypress
        working-directory: analytics-pipeline
